name: image_classifier_app
description: "A Flutter app for image classification with Teachable Machine"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ML & TensorFlow
  tflite_flutter: ^0.12.1
  
  # Camera
  camera: ^0.11.3
  image_picker: ^1.1.2

  # Image processing
  image: ^4.2.0

  # Firebase
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3

  # Permissions
  permission_handler: ^12.0.1

  # HTTP
  http: ^1.1.0

  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  fl_chart: ^1.1.1
  
  # File handling
  path_provider: ^2.1.3
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt